apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: step-ca-data
  namespace: step-ca
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 2Gi
