apiVersion: v1
kind: Secret
metadata:
    name: step-ca-secrets
    namespace: step-ca
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:SRGn5GTVsvn8XOlGPucJBsHzqQl3Ow4D+JwwSuou3fHFn2V0eZ6NKMupsTY=,iv:rPC3Mx1Nk9WsSkg2pV1WoBjWAJRBVRapeYM1Yxn72IM=,tag:liNLF4plxRk1ga/EaEYXJQ==,type:str]
    provisioner_password: ENC[AES256_GCM,data:O3Qu4Vuhk7OTqWJ12hc9RD6vhfjiCXWU3Apf07MckMRr+iRmoGvir+tsSLk=,iv:CoAKGsGlWNqEOyfAvOYuzzrAmC58iyfOGcQUPXM/dS8=,tag:EznMxoazH0UZNGA1n9voRg==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiaXJsN0tmNXh1c2g2QWpz
            c2ZqTnpxSk5KQ0JWUTA1dWp5N1FBM2lOU2pNCm0wbWdCSkQvWGdnMXErWDhXSi96
            YTBqQzhDQXM0a1AyKzR5cGNqVjBxbzQKLS0tIGlld2EvVGFuUWhWeEx4VzZKd0Mx
            UmR3VllzZ0M0MlBCbW9jd1REUCtlYkkK92MOQfW2R50uTLhL/OS53xzX4oIADY6o
            EKK1kGNZN3ZT4i5aFvbQr9A1F+BIES+hvbs6SMTgUclK8KpmNp8v4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T19:45:27Z"
    mac: ENC[AES256_GCM,data:Ueb1c3RUs5FHpZVOeDyjejwIPB4XOwiw/7ksePZFHJDZZiCJJDzCIuANQW555E4ut8VYwD73Mq5WTpNFNXF7gDokWObLVPbExgWCVODbKl7XLzLcVRFVzEfqzzm3dCdXhJwKq3vLoZ7r+tKCwmK9rSB6ZI/5VuNfhZ4+3UIVdGs=,iv:5Ll6Cd1DwIjQBPFmUmQzB4Gx6+AuhTGPNdKZwyZkWuc=,tag:tUJE6O5LKwGH8TztkCwtLw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
