apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server
  namespace: argocd-dev
  annotations:
    argocd.argoproj.io/sync-wave: "20"
    cert-manager.io/cluster-issuer: step-ca-int-acme
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: nginx-private
  tls:
    - hosts:
        - argocd-dev.int.blackcircuit.ca
      secretName: argocd-dev-int-blackcircuit-ca-tls
  rules:
    - host: argocd-dev.int.blackcircuit.ca
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 443
