apiVersion: v1
kind: Secret
metadata:
    name: repo-git-ssh
    namespace: argocd-dev
    labels:
        argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
    url: ENC[AES256_GCM,data:f79dsbY+HvdAmza7/uEXzY8hJujgPre/qlkaTNmoR+a9FmWzRev7V0/9vbpmhtMQhEbMN6aaa1s=,iv:pP218LJBpvDhiq46LpagrYUPoO7XSCJCmwucKPYtI+k=,tag:eEX8KCCNtyVO3SjJzN7eDg==,type:str]
    type: ENC[AES256_GCM,data:6saV,iv:gkUFilT7p1f1AGznVLSt77TRb+5LbMScncLRWGQX9u8=,tag:+rs0OIA2uLmaMGSwsy98Yw==,type:str]
    sshPrivateKey: ENC[AES256_GCM,data:63Ii4jpQLTVATuEEYmHdSoTvA0dIONqtaphqHUNgsA/MBmcP3S/tIULMnbEbEbMMf0dYQ3py/3ZMgMAxs3i3WHuZ5SrumO4B+1C383y76nlq9Q9mcBRTksm1bVGoHmig7F5dqm0FiCoHyHqbo/RCq8pgrsoM0DX8LfRS9NnYXfXx0kORp/w7xuTJYQfTyzrXb5vgU4szQ20Z9rMTjoErGTLZWzbXa070bnLzjDLmUYJS6gAvrGsup+YiuB3oDc/kq+QPOk7XqZmTHZHy8dDsfYZm6bICP2CpRVSf+rPzMQUZlSrtLsnS4FzE5KWz6VB4Rm/6FwhPYzGtiFs66cmJMHtSvFmau7Tbk076YZ+6hlW1rPupwJ369THKnKXNh3+0EMxOffKkjJvM2Rk+L79EUuznJdLhIfqwEMcm17QX9fL9m6Bi3ldJ3EODtU6MnuZ1lE/6wG37id/3eum5HxvYcs3K2l1u2mwToz30R+Lm3OYiqwV7bGvAhk94Y5JdOn6ppgJhGbXVfbi/zeUIZXPW,iv:fuciBsUTNJpMBLSrc3pQfmeQkOr6OgLECA2LIGUOjfo=,tag:SBxAd5Lj7IjnG/I10SgJ5A==,type:str]
    known_hosts: ENC[AES256_GCM,data:zrdiuT3oeBiKd+yvIsXIsItC5uCS2/2UmUMZ+jTDag+JZTIANgQl8ihVq4cd36g0a02m9mTnVsdqzXRILDki6Z5TukdUCd9nKJ7hJu1SBJ4F3aMEqmqSZgw8KmsTpQx0QX9bgXtZ6jKO2j/QsjJReXov21I2zS+9FIZn3AXvK9cch0IPhMOaG9fFAItRhbMs7UQGZzdgCQqM76kWrL491p1GUeRktV9iQsiLYCZnsfA6vFgR+NUGhPM4neAsmujpyC4SRuMyRrFDorma38QLqlVc8y1kXwTpUlTmAMsQbjezKzF0JyUaPOrta8SM4PJm26Eyk7rhpBuf7gR3yIxQA59fkAdjG3cgg2n/E9JhlBCy655kmwtttT3r3rOC3MA44mFsxk5eQPJrFWVmJlk4Qz+jYe2p4dMFEphpxoCiwxKSSW15xwMWPYh04PTImAJm51QSBapesqyLHO/tN9u08dkz7jPH5OTp1+rBGwndEIsHyJUo8nidaARLdkMCbOB39MKOK6TLmHiCt2fj7x9JjpssbviKD4eAYhxDcSqn809QaX3fe8//9Q7nRq74HIFQIWhaskSVWDz1dmoR+5ceJtbFmNQ6kgQU5UYSWwfbF1/nHCEr0es/5FnBOupzkdZCDviBwzIlfUMtDUBrViLqZK7H+5ZtQgouDCm9MQ4BW4pceNdRTcKuYOBqYWIjnRiNZ0h1LUzV4E+X1tQ2p76JvS3OdrztMVDvXw8PBSag9XE8oTz4obQUqyg/Brw0eAFtMCf8nIAnm6mqPIp9X9OoHGhW3+fhh1tNp7aLLKyq3NEb3i+EMy4cR8zq8JG1K+ovHuLgy9XXUSyPZUg4wdPI4gD9eyf2RyghAd4zTf7w5qAovs7nHpRzxFl9REJIAS2CxVg1JgoQ4bM32WThP5cyUUsgk6fP2X43iUzxKtjbCSdV6GUTmqaQWFYeg3IzGWIBdicxpOv79LKmWpcBUZc0F7AQ2lPImZVSiOzSxiPvCkY+aK+9xTDHnvf6zSvE266Ky5Hr+MOi9Tu0H14YUD64nc2on7ss8jBggyZhBWP6K4JD0s2B8eBTr7j4GR6VmXDSfeHl+9puLI2Ha8s=,iv:kTwVh8TzdFwb3yGOIa2zqTavRVLmD8WjM3TzH6TtQis=,tag:c6l31hwKZyzUMufzooRmwg==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6UUdCdjkrd0RVakF6dmgv
            WmtpNnUwOUVkNWxBaVRCUEM4bWtjbTk3STNJCmpXOWFLZkhFVXhJc3VEWlVIMHdq
            UlIrV29SbzE5eXpneFhwalFwSzF3Mk0KLS0tIHNzOTBJN1F3NW9BZFhlV3AxZ3or
            QWRvUjhwWHE5T0cvdkFjMEVLU3ZicWcKgsPY6F1qUK2HV9Te/rIXolDSqzQjaGuT
            6JDP0rrRLilFZLH1yYnR8E07m7W07uSiZKKg+jW0fmvlRY0SG/OuCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T19:43:39Z"
    mac: ENC[AES256_GCM,data:iVAsXv1NNiVKBSdVrkg2qoHbznYtTfq7EYZm9aCfHz3xt97wq+FpsHq/eOlSWz45II45Q/lW1CdZM9ng+PEUEmh59Yn7A4bXDVFRbD9QQZQv8511dy5F0z0rJsVNsCLTHuiqlgED+vBVn32PETnKlsVuYmJZ1Z2FKxpz44Tml5w=,iv:5xDazYlBAl/5EbYYCVojLCB6RYh1z/uqA91IVDuM8Xw=,tag:HLDgPjYVCs5FMfXJxXwWNg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
