apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
---
# MetalLB native install (controller + speaker + CRDs)
# Pin the version you want; v0.14.9 is a solid baseline.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/metallb/metallb/v0.14.9/config/manifests/metallb-native.yaml
