apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: blackcircuit
servers: 1
agents: 0

options:
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*
      - arg: --disable=servicelb
        nodeFilters:
          - server:*

  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true

  runtime:
    labels:
      - label: role=dev
        nodeFilters:
          - server:*

network: blackcircuit-net

