apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-internal
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ${GIT_REPO_URL}
    targetRevision: ${REPO_REF}
    path: gitops/manifests/external-dns/internal
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns-internal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

