apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-pools
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  source:
    repoURL: git@github.com:blackcircuit-brian/blackcircuit-infra
    targetRevision: v0.3
    path: gitops/apps/manifests/metallb-pools
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
