apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml

  # Bootstrap platform (iteration 1)
  - ../../../platform/ingress-nginx/overlays/prod
  - ../../../platform/cert-manager/base
  - ../../../platform/step-ca/base
  - ../../../platform/cloudflare-ddns/base
  - ../../../platform/argocd/overlays/prod
