apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    apiToken: ENC[AES256_GCM,data:HQMpYY6+GUnsw/FqiqW4sMQ+K9T9k+PiaU+TjW95oSbDGNuJWrU3Iw==,iv:CEO/7KSMxOHjpoFglPGO3hvydrCmzfxT+xgumZzbeIY=,tag:EiGIWhprwYf0NTsi7RTZVw==,type:str]
sops:
    age:
        - recipient: age1h9s69pj7avnh6ndltevzp636kxcm0rhx59nzxa27ps95awxaeffq3f66ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5WnZRNDlUSHBXb21lc2R6
            T2Q0OStNMUVRQWVjQnhvODgySE9nRlZoNlJvCmtCN3A0WXJ1RkNXVEMzRVFLM3dy
            SDFMUnpEVC9BT0tORmhZb3JmL2NBWVkKLS0tICtnV2dmbWczcWtIdnBka3g2QUVy
            ZmdVQ0dJSVRyU1FucWFxNkxYcmFyaGsKfi8YazWxyoRLwJm1eBcOjlVRRaMdp0ct
            5CAQvpMvPOuTAenVN4y01WXaJ2+w5wxOV38eRdzqJX4TJ8gjAVd/ew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-05T22:50:10Z"
    mac: ENC[AES256_GCM,data:E5WxBwMh+ZXGNWI2MTx/R/SOsDRy8oKhkgxcZmt2poTyqefxJZZal9LMvXjnBA2vEnwnmlSRe55H6HjFIU42BTJtfnRh9l7hqtqnnT/Xvenv3H/JRim0FThgik4Ddrk2+FgOzXsPgvbmgBlm8n1683kOOMtRJq6waG2XVAcZpRU=,iv:Z+bnazuuX/ejaztgyw84bPf7iULUufvHrMobQ67HqiE=,tag:B1ulWp2jkOnNMcVa5S6DBA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
