apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml

  # Bootstrap platform (iteration 1)
  - ../../../platform/ingress-nginx/overlays/dev
  - ../../../platform/cert-manager/core
  - ../../../platform/cert-manager/issuers
  - ../../../platform/storage/base
  - ../../../platform/step-ca/base
  - ../../../platform/argocd/overlays/dev
