apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml

  # Bootstrap platform (iteration 1)
  - ../../../platform/metallb/overlays/dev
  - ../../../platform/ingress-nginx/overlays/dev
  - ../../../platform/argocd/overlays/dev
