apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - secrets.enc.yaml

namespace: example-dev
nameSuffix: -dev

patches:
  - path: patch-env.yaml
  - path: patch-replicas.yaml

images:
  - name: ghcr.io/blackcircuit/example
    newTag: dev-latest