apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-issuers
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:blackcircuit-brian/blackcircuit-infra
    targetRevision: main
    path: gitops/apps/foundation/issuers
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

