apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-issuers
spec:
  project: default
  source:
    repoURL: git@github.com:blackcircuit-brian/blackcircuit-infra
    targetRevision: v0.3
    path: gitops/manifests/cert-manager
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

