apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-private
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx-private
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.14.2
    helm:
      releaseName: ingress-nginx-private
      values: |
        controller:
          ingressClassResource:
            name: nginx-private
            enabled: true
            default: false
            controllerValue: "k8s.io/ingress-nginx"
          ingressClass: nginx-private
          service:
            type: LoadBalancer
            externalTrafficPolicy: Local
            annotations:
              metallb.io/address-pool: private
              metallb.io/loadBalancerIPs: "192.168.50.254"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

