apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned
  annotations:
    # Make sure this applies after the cert-manager bits *within this app*
    argocd.argoproj.io/sync-wave: "10"
spec:
  selfSigned: {}
